# Generated by Django 3.1.7 on 2021-04-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryservice', '0002_auto_20210424_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryservicer',
            name='ratings',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=1, null=True),
        ),
    ]
