# Generated by Django 3.1.7 on 2021-04-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210426_1431'),
        ('deliveryservice', '0004_auto_20210425_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryservicerprofile',
            name='ordersTaken',
            field=models.ManyToManyField(blank=True, default='0', to='order.Order'),
        ),
    ]
