# Generated by Django 3.1.7 on 2021-04-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryservice', '0005_deliveryservicerprofile_orderstaken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryservicerprofile',
            name='ordersTaken',
        ),
    ]
