# Generated by Django 3.1.7 on 2021-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210426_1549'),
        ('deliveryservice', '0006_remove_deliveryservicerprofile_orderstaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryservicer',
            name='mydeliveries',
            field=models.ManyToManyField(blank=True, default='0', to='order.Order'),
        ),
    ]
