# Generated by Django 3.1.7 on 2021-04-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryservice', '0008_deliveryservicerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryservicer',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
