# Generated by Django 3.1.7 on 2021-05-01 17:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopowner', '0002_joincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='joincode',
            name='createdby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby', to='shopowner.shopowner'),
        ),
        migrations.AddField(
            model_name='joincode',
            name='joiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joiner', to='shopowner.shopowner'),
        ),
        migrations.AddField(
            model_name='joincode',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joincode',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
