# Generated by Django 3.1.7 on 2021-04-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210421_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, to='customer.DeliveryAddress'),
        ),
    ]
