# Generated by Django 3.1.7 on 2021-04-23 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210423_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile'),
        ),
    ]
