# Generated by Django 3.1.7 on 2021-04-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_customer'),
        ('customer', '0006_customerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cart'),
        ),
        migrations.AddField(
            model_name='customer',
            name='myorders',
            field=models.ManyToManyField(blank=True, null=True, to='order.Order'),
        ),
    ]
