# Generated by Django 3.1.7 on 2021-04-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_customer'),
        ('customer', '0007_auto_20210426_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.cart'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='myorders',
            field=models.ManyToManyField(blank=True, to='order.Order'),
        ),
    ]
