# Generated by Django 3.1.7 on 2021-04-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_customer'),
        ('customer', '0009_remove_customer_myorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='myorders',
            field=models.ManyToManyField(blank=True, to='order.Order'),
        ),
    ]
