# Generated by Django 3.1.7 on 2021-04-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210426_1422'),
        ('customer', '0011_remove_customer_myorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='myorders',
            field=models.ManyToManyField(blank=True, to='order.Order'),
        ),
    ]
