# Generated by Django 3.1.7 on 2021-04-26 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210423_2326'),
        ('deliveryservice', '0004_auto_20210425_1130'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryservicer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deliveryservice.deliveryservicer'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('notplaced', 'notplaced'), ('placed', 'placed'), ('delivery', 'delivery'), ('reached', 'reached'), ('cancelled', 'cancelled')], default='notplaced', max_length=10, null=True),
        ),
    ]
