# Generated by Django 3.1.7 on 2021-04-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210426_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(default='empty', to='order.CartItem'),
        ),
    ]
