# Generated by Django 3.1.7 on 2021-04-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210426_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliveryservicer',
            new_name='ordershipper',
        ),
    ]
