# Generated by Django 3.1.7 on 2021-04-27 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_toaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placedon',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
